### PR TITLE
32bit partually working

### PR DESCRIPTION
**Pull request by bitten2up**
if you want assets https://app.bitten2up.dev/srb2.apk this is a rolling build, so expect some instability, will comment when it updates, if your game crashes comment with exactly what you did to crash it

known crashes right now:
* dont try netgames, it will crash idk why

### CODE REVIEW

**Comment by bitten2up** [comment]
shoot ment to make this a draft

**Comment by bitten2up** [comment]
god damn thats a lot of issues for this one bug

**Comment by bitten2up** [comment]
updated link with latest commit

**Comment by Robot20Fox10Dragon30** [comment]
Спасибо работает

**Comment by Robot20Fox10Dragon30** [comment]
Есть конечно проблема с тем что не может выбрать lua ну на игровой прогресс это не влияет

**Comment by Robot20Fox10Dragon30** [comment]
Есть вторая проблема это проблема с моделями они в перемешку идут

**Comment by bitten2up** [comment]
translating this again:
first message: thanks It works
second message from what i can tell, correct me if im wrong here: There's an issue that i cannot choose lua but it doesn’t change game progress
third message: There is a second problem, this is a problem with models, they are mixed up

> There is a second problem, this is a problem with models, they are mixed up
> Есть вторая проблема это проблема с моделями они в перемешку идут

yeah, that's a problem with 2.2.11, i haven't gone to fixing it because I'm focusing on the 32 bit support right now
да, это проблема с 2.2.11, я не стал ее исправлять, потому что сейчас сосредоточен на поддержке 32-битной версии

**Comment by Robot20Fox10Dragon30** [comment]
Oh ok

**Comment by Robot20Fox10Dragon30** [comment]
Во время игры за Сильвера Я заметил что при использовании полёта на скорости он выдаёт сообщение Warning cannot change lua но способность работает

**Comment by bitten2up** [comment]
> 

intresting, never seen that before

**Comment by yipeeXDw** [comment]
But how do i get my model pack working?

**Comment by Feedys1234** [comment]
No puedo entrar al enlace

**Comment by bitten2up** [comment]
> No puedo entrar al enlace

fixed

**Comment by yipeeXDw** [comment]
Hey dude i just figure out how to fix them, just move the model files to the srb2 folder (android/data/org.stjr.srb2/files) the only bad thing is that the addon models doesn't work but pretty cool

**Comment by edotdot** [comment]
Hi @bitten2up! We pushed commit d1100bd39c799ec4d2b561790b500dbbd9526e53 and added you as a co-author.

**Comment by sonicfan01** [comment]
Hey @bitten2up can you actually make your version of srb2 have uncapped framerates please and fix the netgames crash and it dosent crash for me in the netgames

**Comment by bitten2up** [comment]
> Hey @bitten2up can you actually make your version of srb2 have uncapped framerates please and fix the netgames crash and it dosent crash for me in the netgames

what

**Comment by sonicfan01** [comment]
What do you mean by what

**Comment by bitten2up** [comment]
> What do you mean by what

you asking the question in a way that i can't understand what you are asking

**Comment by sonicfan01** [comment]
I mean that srb2 2.2.11 dosent have unccaped framerates wich is 60 and the netgames dosent crash for me can you make the game 60fps please

**Comment by bitten2up** [comment]
> I mean that srb2 2.2.11 dosent have unccaped framerates wich is 60 and the netgames dosent crash for me can you make the game 60fps please

not much better but i think you are trying to say
1. you can't get 60 fps
2. you can play online
for 1 idfk uncapped is merged, and 2 thats based on my own testing

**Comment by sonicfan01** [comment]
Yeah basically

**Comment by sonicfan01** [comment]
Hey bitten2up can you port srb2 2.0.6 to android because i want to play the srb2 riders mod please

**Comment by bitten2up** [comment]
> Hey bitten2up can you port srb2 2.0.6 to android because i want to play the srb2 riders mod please

no

**Comment by sonicfan01** [comment]
Why?

**Comment by bitten2up** [comment]
i have a life

**Comment by Useott** [comment]
I have the feeling i get less fps with this than 2.2.10, but ill try redownloading

**Pull request closed without merging**
